spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/praca
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

